######################################################################
# Automatically generated by qmake (3.0) ?? 4? 14 18:45:52 2016
######################################################################

TEMPLATE = app
TARGET = XFSerialPort
INCLUDEPATH += .

# Input
HEADERS += xfserialport.h
FORMS += xfserialport.ui
SOURCES += main.cpp xfserialport.cpp
